name: ci

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Restore Cached Dependencies
        uses: actions/cache@v3.0.4
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Set Up Performant NPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.2
          run_install: false

      - name: Configure Performant NPM
        run: pnpm config set pnpm-prefix ~/.pnpm/

      - name: Install dependencies 👨🏻‍💻
        run: pnpm i --shamefully-hoist

      - name: Generate Static Content
        run: pnpm run generate
        
      - name: Run Linter
        run: pnpm run lint

